jobs:
  - job: Build
    displayName: Nuke
    pool:
      name: Enterprise Architecture - Default Linux
    steps:
      - checkout: self
        clean: true
        persistCredentials: true
      - task: NuGetToolInstaller@1
        displayName: 'NuGet Tool Installer'
        env:
          NODE_EXTRA_CA_CERTS: /etc/pki/tls/certs/ca-bundle.crt
      - task: NuGetAuthenticate@1
        displayName: 'NuGet Authenticate'
        env:
          NODE_EXTRA_CA_CERTS: /etc/pki/tls/certs/ca-bundle.crt
      - task: Bash@3
        displayName: Run Nuke Default Target
        env:
          NuGetApiKey: $(NUGET_API_KEY)
          NuGetPackageSource: $(NUGET_PACKAGE_SOURCE)
          NuGetPassword: $(NUGET_PASSWORD)
          NuGetUsername: $(NUGET_USERNAME)
        inputs:
          arguments: 'Default'
          filePath: './build.sh'
          targetType: 'filePath'
    workspace:
      clean: all

variables:
  - name: buildConfiguration
    value: "Release"