jobs:
  - job: Nuke
    displayName: 'Nuke'
    pool: Enterprise Architecture - Default Linux
    steps:
      - checkout: self
        clean: true
        persistCredentials: true
      # Uncomment the following line to enable publishing artifacts to the Azure Artifacts feed.
      # - task: NuGetAuthenticate@1
      - task: Bash@3
        displayName: 'Nuke Tool Install'
        inputs:
          script: dotnet tool restore
          targetType: 'inline'
          workingDirectory: '$(Build.SourcesDirectory)'
      - task: Bash@3
        env:
          NuGetApiKey: $(NUGET_API_KEY)
          NuGetPackageSource: $(NUGET_PACKAGE_SOURCE)
        displayName: 'Nuke Build'
        inputs:
          script: dotnet nuke-build
          targetType: 'inline'
          workingDirectory: '$(Build.SourcesDirectory)'
    workspace:
      clean: all

variables:
  - name: buildConfiguration
    value: "Release"
